---
#             _            __          __     ___            _        
#  _ __ _   _| |__  _   _ / /__ _ __ __\ \   / / |_ __ _ ___| | _____ 
# | '__| | | | '_ \| | | | / __| '__/ __| | / /| __/ _` / __| |/ / __|
# | |  | |_| | |_) | |_| | \__ \ | | (__| |/ / | || (_| \__ \   <\__ \
# |_|   \__,_|_.__/ \__, | |___/_|  \___| /_/   \__\__,_|___/_|\_\___/
#                   |___/ \_\          /_/                            
# install-pkg
- name: install-pkg | FreeBSD | Development tools should be installed
  when: ansible_os_family == "FreeBSD"
  pkgng:
    name:  "{{ item }}"
    state: "present"
  with_items:
    - "autoconf"
    - "automake"
    - "gcc"
    - "gettext"
    - "git"
    - "ncurses"
    - "openssl"
    - "patch"
    - "pcre"
    - "readline"

- name: install-pkg | RedHat | Development tools should be installed
  when: ansible_os_family == "RedHat"
  yum:
    state: "present"
    name:
      - "autoconf"
      - "automake"
      - "gcc"
      - "gcc-c++"
      - "gettext"
      - "gettext-devel"
      - "git"
      - "ncurses"
      - "ncurses-devel"
      - "openssl-devel"
      - "patch"
      - "pcre"
      - "pcre-devel"
      - "perl-core"
      - "readline"
      - "readline-devel"

- name: install-pkg | Debian | Development tools should be installed
  when: ansible_os_family == "Debian"
  apt:
    state: "present"
    name:
      - "autotools-dev"
      - "autoconf2.59"
      - "automake1.11"
      - "gcc"
      - "gettext"
      - "git"
      - "libncurses-dev"
      - "libpcre3"
      - "libpcre3-dev"
      - "libreadline6-dev"
      - "libreadline6"
      - "ncurses-dev"
      - "openssl"
      - "patch"

