---
#             _            __          __     ___            _        
#  _ __ _   _| |__  _   _ / /__ _ __ __\ \   / / |_ __ _ ___| | _____ 
# | '__| | | | '_ \| | | | / __| '__/ __| | / /| __/ _` / __| |/ / __|
# | |  | |_| | |_) | |_| | \__ \ | | (__| |/ / | || (_| \__ \   <\__ \
# |_|   \__,_|_.__/ \__, | |___/_|  \___| /_/   \__\__,_|___/_|\_\___/
#                   |___/ \_\          /_/                            
# make-module
- name: make-module | Some rubygems should be installed
  gem:
    name:  "{{ item }}"
    state: "present"
  with_items:
    - bundle

